import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(BASE_DIR, "data")
STATIC_DIR = os.path.join(BASE_DIR, "static")

# 创建必要的目录
for dir in [DATA_DIR, STATIC_DIR]:
    if not os.path.exists(dir):
        os.makedirs(dir)

# 数据库配
DB_PATH = os.path.join(DATA_DIR, "mon.db")

# 监控配置
MON_INTV = 5  # 监控间隔（分钟）
CHART_INTV = 1  # 图表更新间隔（小时）
DATA_KEEP_DAYS = 30  # 数据保留时间（天）

# CDN错误关键词
CDN_ERR_KEYS = [
    "Checking if the site connection is secure",
    "This site can't be reached",
    "502 Bad Gateway",
    "503 Service Temporarily Unavailable",
    "504 Gateway Timeout",
    "520 Web Server Returned an Unknown Error",
    "521 Web Server Is Down",
    "522 Connection Timed Out",
    "523 Origin Is Unreachable",
    "524 A Timeout Occurred",
    "525 SSL Handshake Failed",
    "526 Invalid SSL Certificate",
    "527 Railgun Error",
    "Error 502 (Server Error)",
    "Error 503 (Service Unavailable)",
    "504 Gateway Time-out",
    "509 Bandwidth Limit Exceeded",
    "514 SSL Certificate Error",
    "531 SSL Handshake Failed",
    "532 SSL/TLS Handshake Timeout",
    "533 SSL/TLS Handshake Failed",
    "537 Server Diverted",
    "538 Record Route Full",
    "562 TLS Version Not Supported",
    "563 TLS Version Not Supported",
    "Reference #",
    "AkamaiGHost",
    "Akamai - Error Report",
    "ERROR: The request could not be satisfied",
    "Generated by cloudfront (CloudFront)",
    "Fastly error: unknown domain",
    "Fastly error: 503 backend fetch failed",
    "Google",
    "腾讯云CDN",
    "域名解析失败",
    "域名配置错误",
    "腾讯云提醒您",
    "当前域名已停止CDN服务",
    "阿里云CDN",
    "阿里云提醒您",
    "域名未备案",
    "证书不存在或已过期",
    "域名没有配置CNAME",
    "源站DNS解析失败",
    "源站连接超时",
    "华为云CDN",
    "域名尚未在华为云完成备案",
    "源站健康检查失败",
    "源返回异常",
    "华为云-服务器错误",
    "百度云CDN",
    "域名未在百度云加速",
    "百度云加速服务出错",
    "无法连接到源站",
    "源站访问超时",
    "源站不可用",
    "服务器维护中",
    "域名未备案或备案失效",
    "证书校验失败",
    "站点维护中",
    "访问太频繁",
    "服务暂时不可用",
    "非法访问",
]

# 图表配置
CHART_PERIODS = [24, 168, 720]  # 24小时、7天、30天
# 图表颜色
CHART_COLORS = {"normal": "#2ecc71", "err": "#e74c3c", "no_data": "#95a5a6"}
